[package]
name = "imsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.8"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
eframe = "0.22.0"
egui = "0.22.0"
