name: Test
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings 
    - name: Fmt
      run: cargo fmt --check
